### ISSUE TITLE
Won't pair with Pixel 3a or Raspberry Pi 4

### ISSUE THREAD

**Issue by scruss** [makersmakingchange/LipSync-Wireless#1]
Device is not visible in any bluetooth pairing, red LED on Sparkfun module keeps flashing. Jumper behind BT module is open.

After installing latest firmware, I can see this on serial console:

    LipSync Wireless V1.0 (16 September 2019)
    
     --- 
    
    bluetoothConfigDone: 1
    
    cursorSpeedCounter: 0
    
    cursorDelay: 5
    
    cursorFactor: -1.10
    
    cursorMaxSpeed: 5
    
    yHighComp: 1.12
    
    yLowComp: 1.31
    
    xHighComp: 1.00
    
    xLowComp: 1.14
    
    xHighhMax: 849
    
    xLowMax: 814
    
    yHighMax: 828
    yLowMax: 811

**Comment by scruss** [comment]
Fixed it using suggestion of MMC staff (KM): changed [line 52](https://github.com/makersmakingchange/LipSync-Wireless/blob/master/Software/LipSync_Wireless_Firmware/LipSync_Wireless_Firmware.ino#L52) of LipSync_Wireless_Firmware.ino to

    #define BT_CONFIG_FLAG true

then reflashed Arduino. After letting LipSync start up and run for a few seconds, change the code back to

    #define BT_CONFIG_FLAG false

and upload again. This will configure the Bluetooth board properly.

If you're seeing a Bluetooth device called  *RNBT-xxxx* instead of *LipSyncMouse*, you need to do this.

**Comment by milador** [comment]
@scruss Thanks for looking into this. I am also adding this to serial monitor commands for next update as an alternative method. Did you get it working on raspberry pi 4 as well? We put it in Mouse and keyboard hybrid HID bluetooth profile to get it working with iOS devices. We can probably go back to using mouse HID.
